version: '3'

services:
  web:
    build: .
    image: qertyy/mysite:hub
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'articles'
      MYSQL_USER: 'fordjango'
      MYSQL_PASSWORD: '418284qty'
      MYSQL_ROOT_PASSWORD: '418284qty'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
