# Generated by Django 3.2.5 on 2021-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_link',
            field=models.TextField(default=''),
        ),
    ]
