# Generated by Django 3.2.5 on 2021-08-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_link',
            field=models.CharField(max_length=30),
        ),
    ]
