# Generated by Django 3.2.5 on 2021-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_img_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='article_text',
        ),
        migrations.AddField(
            model_name='question',
            name='header',
            field=models.CharField(default='ERROR: NO HEADER', max_length=50),
            preserve_default=False,
        ),
    ]
