# Generated by Django 3.2.5 on 2021-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210804_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='article_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='img_link',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
