# Generated by Django 3.2.5 on 2021-08-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_testshit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='testshit',
        ),
    ]
