# Generated by Django 3.2.5 on 2021-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_question_testshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='article_img_link',
            field=models.TextField(default='5'),
            preserve_default=False,
        ),
    ]
