# Generated by Django 3.2.7 on 2021-09-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_comment_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userid',
            new_name='user_id',
        ),
    ]
